version: "3"
services:
    karbon-node:
        image: "node:17-alpine3.14"
        container_name: "karbon-node"
        entrypoint: "/bin/sh -c -- \"while true; do sleep 10; done\""
        links:
          - "karbon-mariadb:mariadb.host"
        ports:
          - 8080:8080
        volumes:
            - "./:/karbon"
        working_dir: /karbon
        restart: always
    karbon-mariadb:
        image: "mariadb:10.6"
        container_name: "karbon-mariadb"
        volumes:
            - "._mysql_data_dir/:/var/lib/mysql"
        ports:
          - 3307:3306
        environment:
          - MARIADB_USER
          - MARIADB_PASSWORD
          - MARIADB_DATABASE
          - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
        restart: always